name: Elixir CI
on: push
env:
  MIX_ENV: test
jobs:
  build:
    strategy:
      matrix:
        otp: ["24.0"]
        elixir: ["1.11.4", "1.16.0"]
    name: Test - OTP ${{ matrix.otp }} - Elixir ${{ matrix.elixir }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
